name: GophKeeper

on:
  push:
    branches:
      - '*'
#      - '!master'
  pull_request:
    branches: [main]

jobs:
#  audit job performs a set of checks
  audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
#
#      - name: Check tools versions
#        run: |
#          git version
#          curl -V
#          wget -V
      - name: Cache googleapis repo
        id: cache-googleapis
        uses: actions/cache@v3
        with:
          path: googleapis
          key: ${{ runner.os }}-googleapis

      - name: Git submodule googleapis
        if: steps.cache-googleapis.outputs.cache-hit != 'true'
        run: git submodule add --force https://github.com/googleapis/googleapis

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.19'
          check-latest: true
      - run: go version

      - name: Install protobuf
        run: |
          sudo apt-get update
          sudo apt-get install -y protobuf-compiler
      - run: protoc --version

      - name: Verify dependencies
        run: go mod verify

      - name: Generate
        run: make gen

      - name: Build
        run: go build -v ./...

      - name: Run go vet
        run: go vet ./...

      - name: Install staticcheck
        run: go install honnef.co/go/tools/cmd/staticcheck@latest

      - name: Run staticcheck
        run: staticcheck ./...

      - name: Install golint
        run: go install golang.org/x/lint/golint@latest

      - name: Run golint
        run: golint ./...

      - name: Run tests
        run: go test -race -vet=off ./...